export enum ArticleMutationTypes {
  RESET_STATE = 'RESET_STATE',
  TAG_REMOVE = 'TAG_REMOVE',
  TAG_ADD = 'TAG_ADD',
  SET_ARTICLE = 'SET_ARTICLE',
  FETCH_COMMENTS = 'FETCH_COMMENTS',
  SET_COMMENTS = 'SET_COMMENTS'
}
